apiVersion: v1
kind: Service
metadata:
  name: {{ include "softclient4es-federation.fullname" . }}
  labels:
    {{- include "softclient4es-federation.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: flight-sql
      port: {{ .Values.service.port }}
      targetPort: flight-sql
      protocol: TCP
  selector:
    {{- include "softclient4es-federation.selectorLabels" . | nindent 4 }}
